{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "bizon-platform-lite.fullname" . }}-postgresql
  labels:
    {{- include "bizon-platform-lite.postgresql.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: postgresql
      port: 5432
      targetPort: postgresql
      protocol: TCP
  selector:
    {{- include "bizon-platform-lite.postgresql.selectorLabels" . | nindent 4 }}
{{- end }}
