apiVersion: v1
kind: Service
metadata:
  name: {{ include "bizon-platform-lite.fullname" . }}-ui
  labels:
    {{- include "bizon-platform-lite.ui.labels" . | nindent 4 }}
spec:
  type: {{ .Values.ui.service.type }}
  ports:
    - name: http
      port: {{ .Values.ui.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "bizon-platform-lite.ui.selectorLabels" . | nindent 4 }}
